apiVersion: v1
kind: Service
metadata:
  name: coredns-webhook
  namespace: cert-manager
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: coredns-webhook
